
const generatePDF = async (name) => {
    const { PDFDocument, rgb } = await PDFLib;
    const exBytes = await fetch("./cert.pdf").then(res => {
        return res.arrayBuffer()
    });

    const exFont = await fetch("./Poppins-Medium.ttf").then(res => { 
        return res.arrayBuffer() 
    });
    const pdfDoc = await PDFDocument.load(exBytes);

    pdfDoc.registerFontkit(fontkit); 
    const myFont = await pdfDoc.embedFont(exFont);

    const pages = pdfDoc.getPages();
    const firstPage = pages[0];
    const { width, height } = firstPage.getSize();

    firstPage.drawText(name, {
        x: 192,
        y: 264,
        size: 34,
        font: myFont,
        color: rgb(1, 1, 1),
    });

    const uri = await pdfDoc.saveAsBase64({ dataUri: true });
saveAs(uri, `Hackprix ${name}.pdf`, { autoBom: true })
    console.log(exBytes)
   // document.querySelector("#certificate").src = uri;

}
const optionsArray = ["Chinmayee Yasaswini",
            "Deekshith Alugubelli",
            "Diya Gour",
            "Mohammed Fahad Nawaz Khan",
            "Mohammed Muzzammil Uddin",
            "Mohd Muqeet",
            "Sai Neeraj",
            "Samad Yaqoob",
            "Shaik Ilyas",
            "Shaik Irfan",
            "Shouraim Ahmed",
            "Tauquir Alam",
            "Gaurav Verma",
            "Narendra Rathore",
            "Prabhat Potdar",
            "Amatul Wadood",
            "Amina Mirza",
            "Anas Basheer",
            "mohammed ali",
            "Pavani Chindala",
            "Prathyusha Yekamba",
            "Faizan Ahmed",
            "Md Hameeduddin",
            "Tameem Alam",
            "Yahya Khan",
            "Adnan Syed",
            "MohammedMujtaba Ahmed.",
            "Murtuza Hashmi",
            "Syed Rehman",
            "Archana Hublikar",
            "GURUKIRAN P",
            "harshika harsha",
            "Sathish S",
            "Mohammed Huzaifah",
            "Mohammed Shameem Sarwar",
            "Shah Hussain",
            "Syed numaan",
            "ankith Deegoju",
            "Dharanidhara Tammina",
            "Shaik Yousuf",
            "Abdul Farhath Mohammad",
            "Anirudh Rakonda",
            "Siddhartha Goud",
            "Ahbar Ali",
            "Md Mustafa",
            "MD Nafees",
            "MDFARHAN KHAN",
            "Gokulpriyan Karthikeyan",
            "Jeyadeepak U R",
            "Mohamed Arbaaz",
            "Kavyasree Polamreddy",
            "Manasa Tellapati",
            "Sivasree Thupalli",
            "Bharath Peddi",
            "Chandra Sekhar",
            "Ganesh Putta",
            "Jaswanth Pillella",
            "Abdul Mannan",
            "Isfar Mohiuddin",
            "Jibran Iqbal",
            "JOHN ABRAHAM",
            "Pranay Chaitanya",
            "vijay varma",
            "Vinesh Naini",
            "Abdullah Shaikh",
            "Ans Khan",
            "Nabeel Shareef",
            "Shaik Addeeb",
            "Hitesh Kukreja",
            "Mehvish Sheikh",
            "Sahaji Chaurasia",
            "Abdul Aziz",
            "Ibad Sajid",
            "Mohammed Anas",
            "Syed Muzammil",
            "Hanshith Chandragiri",
            "Himaja Sayari",
            "Nidhitha Thangallapally",
            "Rithvika Keerthi",
            "Mohammed Muqsith Ali Khan",
            "Rashid Mahmood",
            "Arham Khan",
            "Mohammed Azaan",
            "Mohd Jawwad",
            "Anil Kumar",
            "Lakshmi Aturu",
            "Rahul Pillanagrovi",
            "Thupalli Yuvasree",
            "Ihsan Shaik",
            "Sidra Aleem",
            "Syeda Zoya",
            "bharath k",
            "Dhurkesh B",
            "GOKUL KANISHK",
            "KARTHIKEYAN T",
            "Asma Khanam",
            "Mohamed Vaiz",
            "Mohammed Ameer",
            "Syed Tajuddin",
            "Abdur farooqui",
            "Mohammed Faisal Parvez",
            "Mohammed Ghouse",
            "Mohammed-Riyan Nazeer",
            "KUMKUM GEHLOT",
            "Ramachandra Bharadwaj",
            "Saloni Sharma",
            "Somanath Nayak",
            "Bhanuprasad Chunchu",
            "Soumya Dwivedi",
            "Sreedwep Sharma",
            "Abdul Muqtadir",
            "Muqtadir Quadri",
            "Sumaiya Fathima",
            "Syed Imaaz Ali",
            "Adeeba Farooq",
            "Ayaan Khan",
            "Sania Mohammadi",
            "Thaizia Shaikh",
            "Salma Sanubar",
            "Sameera Begum",
            "Tarannum Afreen",
            "Zeenath Kousar",
            "Abdul Rahman Abdul Raheem Mohammed",
            "Mohammed Abdul Raheem",
            "Mohammed Adil",
            "Abrar Sharif",
            "Asfaan Hussain",
            "Mohammed AbdulJunaid",
            "Kelvin Patel",
            "Kothaharsh Vardhan",
            "Sharath Chandra",
            "biradar poonam",
            "Ch. Karuna Jyothi",
            "Laya Reddy",
            "Praneeth Dindigala",
            "Soumik Kondadi",
            "Teesa Reddy",
            "Anviksha Pallati",
            "NagaRaj Neelam",
            "Nissi Bandi",
            "Rithwik Chimmani",
            "Grandhi Praveen",
            "Nagarapu Sandeep",
            "Nandakishor Gopalapuram",
            "Praveen vadlamudi",
            "Burugu Sainitin",
            "mekarthi thanusri",
            "panga arun",
            "B.THARUN REDDY",
            "Irrinki Harsha",
            "Sridhar Kalidindi",
            "Aarav Kumar",
            "Bhuvnesh Richhariya",
            "JayJagdish Kar",
            "Prathmesh Pednekar",
            "Akhila Rachakonda",
            "Hanshitha Cherla",
            "Nathan Busi",
            "Yashasvini DONDULA",
            "Shaik Mastan Vali",
            "Shoeb Mohiuddin",
            "Suleman Msu",
            "Mohd Moiz Uddin Ahmed",
            "Rizwan Ali",
            "Sohaib Samad",
            "Ankitha Joshi",
            "K G SHREYA .",
            "Neerav V Patel",
            "Reshna Nandipi",
            "Mohammed Hasnain",
            "Mohammed Mudassir",
            "Mohammed Abdul Farhan",
            "Mohammed Afraaz Ahmed",
            "Mohammed Raahil Ahmed",
            "Arham Farooq",
            "Mohammed Tauseef Ahmed",
            "Sai Devansh Sai Devansh",
            "Shaistha Aara",
            "ABID MAJID",
            "AFFAN KHAN",
            "Moazzam Mohiuddin",
            "Mohammed Shareef",
            "AmmarAzam Ibrahimi",
            "Mohammed Samee Ullah Khan",
            "Mohammedfaisal Jahangir",
            "Ishaq Ahmed",
            "Mohd Azeem",
            "Sufiyan Mehmood",
            "USMAN KHAN",
            "Anjali Kumari",
            "Mohammed Abdul Haseeb",
            "Mohammed Kaif",
            "Syed Akram",
            "Mohammed Faisal",
            "Mohammed Saif",
            "Talha Hussain",
            "Yameenullah Zain",
            "Ibrahim Khaleel",
            "sujay Pathri",
            "Bhargav Pattanayak",
            "Praneeth Ayla",
            "Saurabh Kumar",
            "Mohammed Naserdastagir",
            "Zaid Uddin",
            "Mohammed Ehteshamul Baqui",
            "Nouman Ajmal Khan",
            "Mohammad Akmal",
            "Sohail Shah",
            "SYED AHMED",
            "Syed Naveed",
            "MABHUSUBHANI SHAIK",
            "Sindhuja Gopu",
            "Madhuri Eampati",
            "Rupa Samala",
            "SaiVivek Dokudu",
            "Vishal Arya Dacha",
            "Md Himayath Ali",
            "Mohammed Muqtadir",
            "Mudassir Uddin",
            "SHAIK ABRAR",
            "Dudekula Sohel",
            "Shaik Kaleem",
            "Aqdas Ahmed",
            "Kalam Khan",
            "Maryam Mateen",
            "Mohammed Mubashiruddin",
            "Manoj Reddy",
            "sai charan",
            "sai shashank",
            "Sainath S",
            "Sharath Chandra Chinnarigari",
            "Chakradhar Amingad",
            "Joel Thaduri",
            "morathoti rahul",
            "Sanjana Aravind",
            "ABDUL RAZZAK",
            "ANAS FARHAN",
            "MD JAVEED_KHAN",
            "Ahmedqudsi GhouseAlikhan",
            "Mohammed Waseemuddin",
            "Mohd Amaan",
            "Omar Kaiser",
            "AKASH PENTALA",
            "K.Ajay Goud",
            "Madugula Likhith",
            "ROHITH NAIDU",
            "Abhishek Lodhi",
            "Indal Lodhi",
            "Raj lodhi",
            "Alvira _",
            "RAFEIA MAHEEN",
            "Aavula Anusha",
            "BHUKYA GEETHIKA",
            "Satya Reddy",
            "Rugved Wankhade",
            "Sheldon Chettiar",
            "Abdul Taha",
            "Jawad Mohd",
            "Mohammed Arsalaan",
            "Roshan Zameer",
            "Dheeraj Reddy",
            "Sanjay Agamamidi",
            "Sirichandan Anumandla",
            "Sudeep Gudipalli",
            "Abdul Rahman",
            "Mahmood Ali",
            "Muzmmmil Ather",
            "Syed Muheed",
            "Nishant Tiwari",
            "Shiwansh Tiwari",
            "AKHIL MAHESWARAM",
            "Kiran alex Challagiri",
            "kunal idnani",
            "Asritha Indira Palchuru",
            "Naresh C",
            "Ankit Bhad",
            "Aryan Khokle",
            "Girija Chachada",
            "Kunika Bhutada",
            "Md MuqeetAli",
            "Mohammed Shafian Ali Khan",
            "Mohd Abuzar",
            "Rushikesh Ponnala",
            "SadhaShiva Aeshala",
            "Saipavan Middela",
            "Srikarnivas Yerra",
            "Ankita Rolla",
            "Kumaran S",
            "sarthak Rath",
            "Varsha .",
            "Aravind Pulluri",
            "Sneha Uppula",
            "Tejashwini Pilli",
            "Affan Asif",
            "Ibraheem Farooq",
            "Masood Sharief",
            "Shafaq Hussain",
            "charan reddy",
            "PremSai Kota",
            "Shivamani Gali",
            "Srinivas Gogula",
            "Mohammed Ismail",
            "S ADITHIYA",
            "Sayyad Shakil",
            "Swayam Tiwari",
            "Insiya Maryam",
            "Maria Ashfaq",
            "Nameera Nousheen",
            "Saniya Arshad",
            "Mohammad Vahaj ur Rahman",
            "Mohammed Musab Umayr",
            "Nahid Sami",
            "Syed Omer Shah",
            "Aabhash sinha",
            "Aditya Kaushik",
            "Hrishi Rathore",
            "Vineet Pandey",
            "Ausaf Nouman",
            "Maryam Asad",
            "Syed Humaid",
            "ZOYA Ali",
            "Bilal Hussain",
            "Danish Mohiuddin",
            "Uzair Khan",
            "N Raghuveer",
            "Sai Tejaswini",
            "sandeepkumarreddy Tavva",
            "k sanath",
            "P NISHANT",
            "S.chandrakanth Reddy",
            "YERUKALA RAMAKRISHNA",
            "Chaitanya Gatreddi",
            "Manvitha Maddula",
            "Keerthi Boga",
            "Pramod Kumar",
            "Vigneshwar SametiThirumani",
            "Charan Voore",
            "E.Y.S.V.S ABHAY",
            "Rishitha Rumandla",
            "Shravya Bojja",
            "FARDEEN KHAN",
            "Mohamed Yaser",
            "MOHD KHIZER",
            "Ahmed Bahattab",
            "Mohammad Uzaafar",
            "Nawaz Ahmed",
            "SyedHameed Uddin",
            "Dhanush NarasimhaRao",
            "mani chandra",
            "md yaseen",
            "Rajagiri Likhitha",
            "A Chandra Kishan Singha",
            "Mahima Yadav",
            "Shahir Bilagi",
            "Velupugonda BhavaniKrishna",
            "Vikhyath Rai",
            "Yash Shetty",
            "Balakrishna Veldi",
            "Hemanth Kumar",
            "NIRUPREDDY MARAMREDDY",
            "Pasupula Muralidhar",
            "JADAV KESHAV",
            "Mohammed AbdurRasheed",
            "MONISH BALANI",
            "Rohith Singh",
            "KAMALESH D",
            "Monishraj H",
            "Kotha Murali Krishna",
            "Neeraj Karatmal",
            "Sai Ram Naraboina",
            "Varun Kumar Gajjala",
            "Aneesh Sai",
            "Hemanth Mudivarti",
            "Syeda Bareerah",
            "Zobia Sultana"];



// Get the dropdown content container
const dropdownContent = document.getElementById("myDropdown");
//const btn = document.getElementById("button");
username = "test";

const buttonn = document.querySelector("#button1");


// Populate options dynamically
optionsArray.forEach((optionText) => {
    const optionElement = document.createElement("a");
    optionElement.textContent = optionText;
    optionElement.href = "#"; // You can set a link if needed
    dropdownContent.appendChild(optionElement);
});

// Event listener for option selection
dropdownContent.addEventListener("click", (event) => {
    if (event.target.tagName === "A") {
        const selectedOption = event.target.textContent;
        document.getElementsByClassName("dropbtn")[0].textContent = selectedOption;
        username = selectedOption;
        console.log(`Selected option: ${username}`);
        // Use the selectedOption as needed (e.g., pass it to a function)
    }

});

    buttonn.addEventListener("click", () => {

        if(username == "test"){
            alert("Please select your name");

        }
        else{
            console.log("kk");
            generatePDF(username);
        }
})

// Filter function for search
function filterFunction() {
    const input = document.getElementById("myInput");
    const filter = input.value.toUpperCase();
    const options = dropdownContent.getElementsByTagName("a");

    for (let i = 0; i < options.length; i++) {
        const optionText = options[i].textContent || options[i].innerText;
        if (optionText.toUpperCase().includes(filter)) {
            options[i].style.display = "block";
        } else {
            options[i].style.display = "none";
        }
    }
}

//generatePDF("Test Name")